### ISSUE TITLE
Cannot be used on Bukkit and Forge hybrid server

### ISSUE THREAD

**Issue by zoe-may** [giovanni-bozzano/betonquest-gui-plugin#3]
Server: catserver
version: 1.16.5
Plugin version: betonquestgui-plugin-1.1.0-BQ1.x
BetonQuest version: 1.12.9

Using this plug-in on the Bukkit and Forge hybrid server will cause the client to prompt "connection closed - mismatched mod channel list", even if the "BetonQuest GUI" mod is put into the server's mods folder, it is useless，because the plugin will report an error, as follows
![image](https://user-images.githubusercontent.com/71170887/213805047-532fc7cd-31d1-40f7-ab60-ec5d02dc297f.png)
Text edition：
` Could not load 'plugins\betonquestgui-plugin-1.1.0-BQ1.x.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: main class
com.giovannibozzano.betonquestgui.BetonQuestGui' does not extend JavaPlugin
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:101) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:304) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:298) ~[forge:1.16.5-dd026270]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:209) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:737) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class com.giovannibozzano.betonquestgui.BetonQuestGui
	at java.lang.Class.asSubclass(Class.java:3924) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:99) ~[forge:?]
	... 8 more`

In addition, the version of BetonQuest I use is 1.12.9. Because my client does not support the latest beta version of BetonQuest, I use Full version (I don't know if this has any impact)

![image](https://user-images.githubusercontent.com/71170887/213793161-3b89b72d-2f9b-42a7-a2ae-3b111c8f875a.png)

Sorry, my mother tongue is not English. If you don't understand my description, please ask me:)

**Comment by Japerz12138** [comment]
Yeah, I got the same exact problem by using Catserver
